# Generated by Django 5.2.1 on 2025-06-10 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='learning.course'),
        ),
        migrations.AddField(
            model_name='module',
            name='material_pdf',
            field=models.FileField(blank=True, null=True, upload_to='module_pdfs/'),
        ),
    ]
