# Generated by Django 5.2.1 on 2025-06-11 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_badge_course_module_material_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='videolink',
            field=models.TextField(blank=True, null=True),
        ),
    ]
