# Generated by Django 5.2.1 on 2025-06-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0002_badge_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='course',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='module',
        ),
    ]
