# Generated by Django 5.2.1 on 2025-06-12 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dbteacher1',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_email', models.EmailField(max_length=254, unique=True)),
                ('t_password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dbstudent1',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('s_profilepicture', models.ImageField(blank=True, null=True, upload_to='profilepics/')),
                ('s_firstname', models.CharField(max_length=50)),
                ('s_lastname', models.CharField(max_length=50)),
                ('s_email', models.EmailField(max_length=254, unique=True)),
                ('s_phonenumber', models.BigIntegerField()),
                ('s_guardianphonenumber', models.BigIntegerField()),
                ('s_qualification', models.TextField()),
                ('s_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('s_password', models.CharField(blank=True, max_length=128)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='learning.course')),
            ],
        ),
    ]
